// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated from permissions.yaml

export enum Permission {
  AUTH_LOGIN = 'auth.login',
  AUTH_LOGOUT = 'auth.logout',
  ORG_READ = 'org.read',
  ORG_UPDATE = 'org.update',
  BRANCH_READ = 'branch.read',
  BRANCH_CREATE = 'branch.create',
  BRANCH_UPDATE = 'branch.update',
  BRANCH_DELETE = 'branch.delete',
  USER_READ = 'user.read',
  USER_CREATE = 'user.create',
  USER_UPDATE = 'user.update',
  ROLE_READ = 'role.read',
  ROLE_ASSIGN = 'role.assign',
  PRODUCT_READ = 'product.read',
  PRODUCT_CREATE = 'product.create',
  PRODUCT_UPDATE = 'product.update',
  PRODUCT_DELETE = 'product.delete',
  PRODUCT_PRICE.UPDATE = 'product.price.update',
  CATEGORY_READ = 'category.read',
  CATEGORY_CREATE = 'category.create',
  CATEGORY_UPDATE = 'category.update',
  CATEGORY_DELETE = 'category.delete',
  BRAND_READ = 'brand.read',
  BRAND_CREATE = 'brand.create',
  BRAND_UPDATE = 'brand.update',
  BRAND_DELETE = 'brand.delete',
  UNIT_READ = 'unit.read',
  UNIT_CREATE = 'unit.create',
  UNIT_UPDATE = 'unit.update',
  UNIT_DELETE = 'unit.delete',
  PRICE_LIST_READ = 'price_list.read',
  PRICE_LIST_CREATE = 'price_list.create',
  PRICE_LIST_UPDATE = 'price_list.update',
  PRICE_LIST_DELETE = 'price_list.delete',
  INVENTORY_READ = 'inventory.read',
  INVENTORY_ADJUST = 'inventory.adjust',
  INVENTORY_COUNT = 'inventory.count',
  POS_ACCESS = 'pos.access',
  ORDER_CREATE = 'order.create',
  ORDER_DISCOUNT = 'order.discount',
  AUDIT_READ = 'audit.read',
}
