packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'
  - 'services/*'
overrides:
  react: '^19.2.7'
  react-dom: '^19.2.7'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
